### PR TITLE
Star Rating Assignment Added

### PR DESCRIPTION
**Pull request by Dhanu-kokate**
Star Rating Assignment has been done .

### CODE REVIEW

**Comment by HarishBoke** [comment]
I could see only one file checked-in. so could not review other files @Dhanu-kokate

**Comment by HarishBoke** [comment]
Spelling mistake: https://github.com/HarishBoke/lions-sessions/blob/master/star-rating/Dhanashri/script.js#L3 i guess it should be **starCount**

**Comment by HarishBoke** [comment]
we can pass eleAction as parameter on render / Invocation https://github.com/HarishBoke/lions-sessions/blob/master/star-rating/Dhanashri/script.js#L18

**Comment by HarishBoke** [comment]
Once we rate, we can not undo rating, If only one start it should toggle

**Comment by HarishBoke** [comment]
I don't think we need 2 loop + each click on star should not render this 2 loops.  Can we think of better approach?

**Review by HarishBoke — CHANGES_REQUESTED** [review]
Added comments in conversation.  Please check

**Comment by Dhanu-kokate** [comment]
> 
> 
> Once we rate, we can not undo rating, If only one start it should toggle

I can't understand

**Comment by HarishBoke** [comment]
@Dhanu-kokate  Looks good, I have one concern on reset behavior but that may be additional work for now whatever is done looks good.

**Review by HarishBoke — APPROVED** [review]
@Dhanu-kokate  Looks good, I have one concern on reset behavior but that may be additional work for now whatever is done looks good.

**Pull request merged**
